{ config, pkgs, lib, ... }:

{
  imports = [
    ./hardware-configuration.nix   # generated by nixos-generate-config, machine-specific
  ];

  # ─── Boot loader ───────────────────────────────────────────────────────────
  # UEFI system with systemd-boot (simpler and correct for NVMe/UEFI)
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # ─── State version ─────────────────────────────────────────────────────────
  # Set this to the NixOS version you FIRST installed. Do not bump it later —
  # it guards stateful data migrations, not the packages you get.
  system.stateVersion = "25.05";

  # ─── Nix settings ──────────────────────────────────────────────────────────
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store = true;
  };

  # ─── Allow unfree packages (PhpStorm, etc.) ────────────────────────────────
  nixpkgs.config.allowUnfree = true;

  # ─── GNOME Desktop ─────────────────────────────────────────────────────────
  services.xserver.enable = true;
  services.displayManager.gdm.enable = true;
  services.displayManager.gdm.wayland = true;
  services.desktopManager.gnome.enable = true;

  # Trim default GNOME bloat — remove what you don't want
  environment.gnome.excludePackages = with pkgs; [
    gnome-tour
    gnome-connections
    epiphany        # GNOME Web (we're using Firefox)
    geary           # GNOME Mail
    gnome-weather
    gnome-maps
    gnome-music
  ];

  # ─── System packages ───────────────────────────────────────────────────────
  environment.systemPackages = with pkgs; [

    # --- PHP 8.3 with common extensions ---
    (php83.buildEnv {
      extensions = ({ enabled, all }: enabled ++ (with all; [
        bcmath
        curl
        dom
        gd
        intl
        mbstring
        mysqli
        opcache
        openssl
        pdo
        pdo_mysql
        pdo_pgsql
        pgsql
        redis
        tokenizer
        xml
        zip
      ]));
      extraConfig = ''
        memory_limit = 512M
        upload_max_filesize = 64M
        post_max_size = 64M
      '';
    })

    # --- Composer ---
    php83Packages.composer

    # --- Node.js (LTS) ---
    nodejs_22

    # --- fnm: Fast Node Manager (nvm replacement for NixOS) ---
    fnm

    # --- Git ---
    git
    git-lfs

    # --- JetBrains PhpStorm ---
    jetbrains.phpstorm

    # --- Firefox ---
    firefox

    # --- eza: modern ls replacement ---
    eza

    # --- Docker CLI tools (daemon is managed as a service below) ---
    docker
    docker-compose

    # --- Useful extras ---
    curl
    wget
    jq
    unzip
  ];

  # ─── Docker daemon ─────────────────────────────────────────────────────────
  virtualisation.docker = {
    enable = true;
    enableOnBoot = true;
  };

  # ─── User ──────────────────────────────────────────────────────────────────
  users.users.hammer = {
    isNormalUser = true;
    shell = pkgs.zsh;        # set zsh as default shell
    extraGroups = [
      "wheel"                # sudo
      "docker"               # run docker without sudo
    ];
  };

  # ─── Zsh + Oh My Zsh ───────────────────────────────────────────────────────
  programs.zsh = {
    enable = true;

    # fnm hook — auto-switches Node version from .nvmrc / .node-version
    interactiveShellInit = ''
      eval "$(fnm env --use-on-cd --shell zsh)"
    '';

    ohMyZsh = {
      enable = true;
      # theme — swap for any theme in ~/.oh-my-zsh/themes/
      theme = "robbyrussell";
      plugins = [
        "git"
        "docker"
        "docker-compose"
        "node"
        "npm"
        "composer"
        "php"
        "fnm"
      ];
    };

    # eza aliases — drop-in replacements for ls
    shellAliases = {
      ls  = "eza --icons";
      ll  = "eza -lh --icons --git";
      la  = "eza -lah --icons --git";
      lt  = "eza --tree --icons --level=2";
      lta = "eza --tree --icons --level=2 -a";
    };
  };

  # ─── Bash fallback — fnm hook ──────────────────────────────────────────────
  programs.bash.interactiveShellInit = ''
    eval "$(fnm env --use-on-cd --shell bash)"
  '';

  # ─── Fonts (GNOME + terminal rendering) ───────────────────────────────────
  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono
    nerd-fonts.fira-code
    inter
    liberation_ttf
  ];
}
