{ config, pkgs, lib, ... }:
{
  imports = [
    ./hardware-configuration.nix   # generated by nixos-generate-config, machine-specific
  ];

  # ─── Boot loader ───────────────────────────────────────────────────────────
  # UEFI system with systemd-boot (simpler and correct for NVMe/UEFI)
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # ─── State version ─────────────────────────────────────────────────────────
  # Set this to the NixOS version you FIRST installed. Do not bump it later —
  # it guards stateful data migrations, not the packages you get.
  system.stateVersion = "25.05";

  # ─── Nix settings ──────────────────────────────────────────────────────────
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store = true;
  };

  # ─── Allow unfree packages (PhpStorm, etc.) ────────────────────────────────
  nixpkgs.config.allowUnfree = true;

  # ─── GNOME Desktop ─────────────────────────────────────────────────────────
  services.xserver.enable = true;
  services.displayManager.gdm.enable = true;
  services.displayManager.gdm.wayland = true;
  services.desktopManager.gnome.enable = true;

  # Trim default GNOME bloat — remove what you don't want
  environment.gnome.excludePackages = with pkgs; [
    gnome-connections
  ];

  # ─── System packages ───────────────────────────────────────────────────────
  environment.systemPackages = with pkgs; [

    # --- PHP 8.3 with common extensions ---
    (php83.buildEnv {
      extensions = ({ enabled, all }: enabled ++ (with all; [
        bcmath
        curl
        dom
        gd
        intl
        mbstring
        mysqli
        opcache
        openssl
        pdo
        pdo_mysql
        pdo_pgsql
        pgsql
        redis
        tokenizer
        xml
        zip
      ]));
      extraConfig = ''
        memory_limit = 512M
        upload_max_filesize = 64M
        post_max_size = 64M
      '';
    })

    # --- Composer ---
    php83Packages.composer

    # --- Node.js (LTS) ---
    nodejs_22

    # --- fnm: Fast Node Manager (nvm replacement for NixOS) ---
    fnm

    # --- Git ---
    git
    git-lfs
    gh          # GitHub CLI

    # --- JetBrains Toolbox (use this to install PhpStorm EAP) ---
    jetbrains-toolbox

    # --- eza: modern ls replacement ---
    eza

    # --- Docker CLI tools (daemon is managed as a service below) ---
    docker
    docker-compose

    # --- Nemo file manager ---
    nemo
    nemo-fileroller      # archive support

    # --- Terminal ---
    kitty

    # --- Useful extras ---
    curl
    wget
    jq
    unzip
  ];

  # ─── Firefox + extensions ─────────────────────────────────────────────────
  programs.firefox = {
    enable = true;
    policies = {
      ExtensionSettings = {
        # 1Password extension — auto-installed, user can manage it
        "{d634138d-c276-4fc8-924b-40a0ea21d284}" = {
          install_url = "https://addons.mozilla.org/firefox/downloads/latest/1password-x-password-manager/latest.xpi";
          installation_mode = "normal_installed";
        };
      };
    };
  };

  # ─── Git ──────────────────────────────────────────────────────────────────
  programs.git = {
    enable = true;
    config = {
      user = {
        name  = "toddmcbrearty";
        email = "todd.mcbrearty@gmail.com";
      };
      init.defaultBranch = "main";
      core = {
        autocrlf = "input";   # on commit: normalize CRLF → LF; on checkout: no change
        eol      = "lf";
      };
      push.autoSetupRemote = true;
      pull.rebase = false;
    };
  };

  # ─── Terminal-─────────────────────────────────────────────────────────────
  programs.kitty = {
    enable = true;
    defaultTerminal = true;
  };
  # ─── Neovim ───────────────────────────────────────────────────────────────
  programs.neovim = {
    enable = true;
    defaultEditor = true;
  };

  # ─── Sudo ─────────────────────────────────────────────────────────────────
  security.sudo = {
    enable = true;
    wheelNeedsPassword = false;  # todd can sudo without a password
  };

  # ─── Docker daemon ─────────────────────────────────────────────────────────
  virtualisation.docker = {
    enable = true;
    enableOnBoot = true;
  };

  # ─── Users ─────────────────────────────────────────────────────────────────
  users.users.todd = {
    isNormalUser = true;
    shell = pkgs.zsh;
    extraGroups = [
      "wheel"
      "audio"
    ];
  };

  users.users.todd = {
    isNormalUser = true;
    shell = pkgs.zsh;        # set zsh as default shell
    extraGroups = [
      "wheel"                # sudo
      "docker"               # run docker without sudo
    ];
  };

  # ─── Zsh + Oh My Zsh ───────────────────────────────────────────────────────
  programs.zsh = {
    enable = true;

    # fnm hook — auto-switches Node version from .nvmrc / .node-version
    interactiveShellInit = ''
      eval "$(fnm env --use-on-cd --shell zsh)"
    '';

    ohMyZsh = {
      enable = true;
      theme = "agnoster";
      plugins = [
        "git"
        "docker"
        "docker-compose"
        "node"
        "npm"
        "composer"
        "fnm"
      ];
    };

    # eza aliases — drop-in replacements for ls
    shellAliases = {
      ls  = "eza --icons";
      ll  = "eza -lh --icons --git";
      la  = "eza -lah --icons --git";
      lt  = "eza --tree --icons --level=2";
      lta = "eza --tree --icons --level=2 -a";
      nbf = "nixos-rebuild switch --flake";
      vi  = "nvim";
      vim = "nvim";
      to-fconf = "cd ~/.config/nix";
    };
  };

  # ─── Create empty ~/.zshrc if it doesn't exist ────────────────────────────
  system.activationScripts.zshrc = {
    text = ''
      if [ ! -d /home/todd ]; then
        mkdir -p /home/todd
        chown todd:users /home/todd
        chmod 700 /home/todd
      fi
      if [ ! -f /home/todd/.zshrc ]; then
        touch /home/todd/.zshrc
        chown todd:users /home/todd/.zshrc
      fi
    '';
    deps = [];
  };

  # ─── Ensure wrappers bin is first in PATH ─────────────────────────────────
  environment.sessionVariables = {
    PATH = [ "/run/wrappers/bin" ];
  };

  # ─── Bash fallback — fnm hook ──────────────────────────────────────────────
  programs.bash.interactiveShellInit = ''
    eval "$(fnm env --use-on-cd --shell bash)"
  '';

  # ─── Fonts (GNOME + terminal rendering) ───────────────────────────────────
  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono
    nerd-fonts.fira-code
    inter
    liberation_ttf
  ];
}
